# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: Linux

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    versionSpec: '11'
    #jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    jdkFile: "/builds/openjdk-11.0.2_linux-x64_bin.tar.gz"
    jdkDestinationDirectory: "/builds/binaries/externals"
    cleanDestinationDirectory: true
    mavenVersionOption: 'Default'
    publishJUnitresults: true
    #testResultFiles: '**/surefire-reports/TEST-*.xml'
    goals: package
    


    

